### PR TITLE
JEDI FORCE

### PR DESCRIPTION
**Pull request by ingen0s**

### CODE REVIEW

**Comment by ingen0s** [comment]
PLease not the _config.yml setting are set to my dev links, we may need a quick strategy call for this to sync properly

**Comment by adam3smith** [comment]
Thanks! any reason we couldn't just switch this right after merging?
And what's `live_base_url` ? This seems like a link to the repo?

**Comment by ingen0s** [comment]
@adam3smith Should be able to switch it over by changing those values to the current repo, I can rework the pull request with the live URIs, I just wanted to make sure that your current config setup was not ignored. The ```live_base_url``` helps generate absolute URLs for links, images, and other assets, so if for any reason things changed links would update accorodingly.

**Comment by ingen0s** [comment]
Closing this pull request draft - opening offical one. Please note the folder structure / config changes when merging.

**Pull request closed without merging**
